/**
 * Core data model. IDs are client-generated UUIDs. All timestamps are epoch
 * milliseconds. Dates that represent a calendar day (not an instant) are
 * stored as 'yyyy-MM-dd' strings so they are immune to timezone drift.
 *
 * Goal/task time model (v2):
 *   - 'scheduled': has a scheduledDateISO ("when I intend to work on this")
 *     and an optional deadlineISO (hard due date). Stays active and becomes
 *     "Late" after its scheduled date passes, until completed or deleted.
 *   - 'weekly': belongs to a custom Saturday–Friday week (currentWeekId).
 *     Rolls forward into the next week if incomplete when the week closes.
 *   - 'today': relevant only on its scheduledDateISO. Does not become Late
 *     and does not roll forward — if missed, it simply stops being active.
 *   - 'recurring': one independent occurrence of a RecurringDefinition. Behaves
 *     like 'scheduled' for Late purposes, but scheduledDateISO is generated by
 *     the recurrence engine rather than chosen per-item.
 */

export type GoalKind = 'scheduled' | 'weekly' | 'today' | 'recurring'

/** @deprecated v1 goal type, retained only for backup-migration typings. */
export type LegacyGoalType = 'daily' | 'weekly'

export type Priority = 'low' | 'medium' | 'high'

export interface Goal {
  id: string
  title: string
  description?: string
  kind: GoalKind

  /**
   * The calendar day this item is intended to be worked on, 'yyyy-MM-dd'.
   * Used by 'scheduled', 'today', and 'recurring' kinds. Unused for 'weekly'.
   */
  scheduledDateISO?: string

  /** Optional hard deadline as a calendar day, 'yyyy-MM-dd'. End-of-day local time. */
  deadlineISO?: string

  priority?: Priority

  createdAt: number
  completedAt: number | null
  completed: boolean

  /** The custom week id this goal was first created in (weekly goals only). Never changes. */
  originalWeekId?: string
  /** The custom week id this goal currently belongs to (weekly goals only). Advances on rollover. */
  currentWeekId?: string

  rolledOver: boolean
  rolloverCount: number

  /** Set only on 'recurring' goals — links an occurrence back to its RecurringDefinition. */
  recurringDefinitionId?: string

  archived: boolean
}

export type RecurrenceType = 'daily' | 'weekly'

/**
 * A recurrence rule that generates independent Goal occurrences (kind:
 * 'recurring'). Occurrences are logically separate rows — completing or
 * missing one never mutates another. See lib/logic/recurrence.ts and
 * lib/db/recurringRunner.ts for the generation algorithm.
 */
export interface RecurringDefinition {
  id: string
  title: string
  description?: string
  recurrenceType: RecurrenceType
  /** Required when recurrenceType === 'weekly'. date-fns getDay() convention: 0=Sun..6=Sat. One or more days. */
  weekdays?: number[]
  priority?: Priority
  active: boolean
  createdAt: number
  /**
   * The last calendar day ('yyyy-MM-dd') occurrence generation has advanced
   * through (inclusive). Generation resumes the day after this cursor, which
   * is what makes repeated runs idempotent and duplicate-proof.
   */
  lastGeneratedThroughISO: string | null
}

export type HabitFrequency = 'daily' | 'weekly'

export interface Habit {
  id: string
  name: string
  description?: string
  frequency: HabitFrequency
  icon?: string
  order: number
  active: boolean
  createdAt: number
}

export interface HabitCompletion {
  id: string
  habitId: string
  /** 'yyyy-MM-dd' for daily habits, weekId for weekly habits. */
  periodId: string
  completedAt: number
}

/**
 * Permanent, immutable per-custom-week aggregate. Never deleted — this is
 * what keeps long-term Analytics accurate after detailed Goal records age
 * out under the retention policy (see lib/logic/cleanup.ts). Analytics for
 * Month/Quarter/Half-Year/Year/All time ranges are computed by summing the
 * snapshots whose `weekStart` falls in the requested calendar range.
 *
 * Field groups below are additive relative to v1: `weeklyPlanned` etc.
 * replace the v1 `totalPlanned` etc. (weekly-goal-only) counters, and
 * `dailyGoalsPlanned/dailyGoalsCompleted` (v1) map onto `todayOnlyPlanned/
 * todayOnlyCompleted` (v2) — see db/db.ts migration for the exact mapping.
 */
export interface WeeklySnapshot {
  weekId: string
  weekStart: number
  weekEnd: number

  // Weekly goals
  weeklyPlanned: number
  weeklyCompleted: number
  weeklyRolledOver: number
  weeklyCompletionPct: number

  // Scheduled tasks whose scheduledDateISO fell in this week
  scheduledPlanned: number
  scheduledCompleted: number
  scheduledCompletedLate: number
  /** Sum of days-late across scheduledCompletedLate items, for computing average lateness. */
  scheduledLateDaysSum: number

  // Today Only tasks assigned to a day in this week
  todayOnlyPlanned: number
  todayOnlyCompleted: number
  todayOnlyMissed: number

  // Recurring occurrences whose scheduledDateISO fell in this week
  recurringPlanned: number
  recurringCompleted: number
  recurringCompletedLate: number
  /** Sum of days-late across recurringCompletedLate items, for computing average lateness. */
  recurringLateDaysSum: number

  // Deadlines (any kind) falling in this week
  deadlinesDue: number
  deadlinesMetOnTime: number
  deadlinesMetLate: number
  deadlinesMissed: number

  createdAt: number
}

export type ThemePreference = 'light' | 'dark' | 'system'

export interface AppSettings {
  id: 'app'
  theme: ThemePreference
  lastWeekIdSeen: string | null
  lastCleanupAt: number | null
  onboarded: boolean
}

/** Shape of an exported backup file. */
export interface BackupFile {
  schemaVersion: number
  exportedAt: number
  appVersion: string
  data: {
    goals: Goal[]
    recurringDefinitions: RecurringDefinition[]
    habits: Habit[]
    habitCompletions: HabitCompletion[]
    weeklySnapshots: WeeklySnapshot[]
    settings: AppSettings[]
  }
}
